# -*- coding: utf-8 -*-
"""Monsoon_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HweDjLhGtYFImhBiiQ8PSoMPjc_WX3p

Problem 1 : Calculator summation problem
"""

#monsoon problem
def CodingChallenge(strParam):
    a, b = strParam.split()

    # Pad shorter string with leading zeros
    max_len = max(len(a), len(b))
    a = a.zfill(max_len)
    b = b.zfill(max_len)

    # Add digit-by-digit without carry
    result = ""
    for da, db in zip(a, b):
        result += str((int(da) + int(db)) % 10)

    return int(result)  # remove leading zeros in final output

# keep this function call here
print(CodingChallenge(input()))

"""Problem 2 :  Array problem"""

def CodingChallenge(strArr):
    arr = [x.strip().strip('"') for x in strArr]
    required = set("012345")
    best_str = ""
    best_i, best_j = None, None

    n = len(arr)
    for i in range(n):
        for j in range(i+2, n):  # ensure non-consecutive
            combined = arr[i] + arr[j]
            if set(combined) >= required:  # contains all 0-5
                if len(combined) > len(best_str) or \
                   (len(combined) == len(best_str) and (best_i is None or i < best_i or (i == best_i and j < best_j))):
                    best_str = combined
                    best_i, best_j = i, j

    return best_str if best_str else "-1"

# Keep this function call here
print(CodingChallenge(input().split(",")))

